version: 3
workdir: .

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"
  - "vendor/.*"
  - "cmd/.*"

allow:
  depOnAnyVendor: true

components:
  # common levels
  cmd: {
    in: cmd/service
  }
  proto: { # proto definitions
    in: pkg/pb/**
  }
  app: {
    in: internal/app/*
  }
  service: {
    in: internal/service/**
  }
  repository: {
    in: internal/domain/*/repository
  }
  provider: {
    in: internal/provider/**
  }
  client: {
    in: internal/client/**
  }
  observer: {
    in: internal/observer
  }
  model: {
    in: internal/models
  }
  logger: {
    in: internal/logger
  }

commonComponents:
  - model
  - logger
deps:
  cmd:
    mayDependOn:
      - proto
      - app
      - service
      - repository
      - provider
      - observer
      - client
  app:
    mayDependOn:
      - proto
      - service
  service:
    mayDependOn:
      - repository
  repository:
    mayDependOn:
      - provider
  provider:
    mayDependOn:
      - client
  observer:
    mayDependOn:
      - service